version: '3'

services:
  server:
    env_file:
      - ./drone_server.env
    image: drone/drone:0.7
    ports:
      - 80:8000
    volumes:
      - ./drone:/var/lib/drone/
      - ./certs:/certs
    restart: always


  agent:
    env_file:
      - ./drone_agent.env
    image: drone/drone:0.7
    command: agent
    depends_on:
      - server
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always
